name: On release test

on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "gh prerelease: $GH_PRERELASE , gh tag: $GH_TAG"
          echo "gh json: $GH_JSON"
          echo "gh event json: $GS_EVENTJSON"
          echo "gh evnet prerelease: $GS_EVENTPRERELEASE"
          echo "gh evnet prerelease3: $GS_EVENTPRERELEASE3"
          echo "gh evnet prerelease4: $GS_EVENTPRERELEASE4"
          echo "gh evnet prerelease5: $GS_EVENTPRERELEASE5"
          echo "gh evnet release: $GS_EVENTRELEASE"
          echo "gs tag2: [$GH_TAG2]"
          echo "gs tag3: [$PRE_RELEASE]"
          echo "gs tag4: [$PRE_RELEASE2]"
        env:
          GH_PRERELASE: ${{ github.event.release.prelease }}
          GH_TAG: ${{ github.event.release.prelease && '--tag next' || ''}}
          GH_JSON: ${{ toJson(github) }}
          GS_EVENTJSON: ${{ toJson(github.event) }}
          GS_EVENTRELEASE: ${{ toJson(github.event.release) }}
          GS_EVENTPRERELEASE: ${{ toJson(github.event.release.prelease) }}
          GS_EVENTPRERELEASE3: ${{ toJson(github.event.release['prelease']) }}
          GS_EVENTPRERELEASE4: ${{ github.event.release['prelease'] }}
          GS_EVENTPRERELEASE5: ${{ github.event.release['prelease'] && 'true' || 'false' }}
          GH_TAG2: ${{ toJson(github.event.release.prelease && '--tag next' || 'na') }}
          PRE_RELEASE: ${{ github.event.release.prerelease }}
          PRE_RELEASE2: ${{ github.event.release }}

          
        
      # Runs a single command using the runners shell
      - name: Run another one-line script
        run: echo "anrls"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script2
        run: |
          echo "Foo"
          echo Add other actions to build,
          echo test, and deploy your project.
